### ISSUE TITLE
Intruction point Compiling the library on the database server

### ISSUE THREAD

**Issue by KOPACb** [osm-search/nominatim-org-site#11]
It seems like after migrating to python there no need in nominatim.so in postgis modules?

https://nominatim.org/release-docs/latest/admin/Advanced-Installations/#option-1-compiling-the-library-on-the-database-server

**Comment by lonvia** [comment]
Yes.

This section has already been updated on [master](https://nominatim.org/release-docs/develop/admin/Advanced-Installations/#using-an-external-postgresql-database). The simplified instructions will be part of the next release.
