### ISSUE TITLE
Ubuntu install instructions

### ISSUE THREAD

**Issue by aaronhance** [osm-search/nominatim-org-site#5]
https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-18/

Wrong file path in apache config, on the following.
<Directory "$USERHOME/Nominatim/build/website">
Alias /nominatim $USERHOME/Nominatim/build/website
Should be:
<Directory "$USERHOME/build/website">
Alias /nominatim $USERHOME/build/website

**Comment by lonvia** [comment]
We normally recommend to create the build directory under the Nominatim directory. So the Apache config is correct. The path where we do `mkdir build` is wrong. Fixed that.
